---
title: "iwc-mayande"
format: html
---

```{r}

# Option 2: Read directly from GitHub

groundhogs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-30/groundhogs.csv')
predictions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-30/predictions.csv')

```

```{r}
library(tidyverse)

groundhogs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-01-30/groundhogs.csv')
predictions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-01-30/predictions.csv')

groundhogs_all <- predictions |> 
   left_join(groundhogs, join_by(id==id))
```



```{r}
# Read Weather Data 
library(readr)
Actual_weather <- read_csv("../../data/data.csv")

```
```{r}
# Read Weather Data 
library(readr)
Actual_weather <- read_csv("../../data/data.csv", skip = 3)
```
```{r}
Actual_weather <- Actual_weather |> 
  mutate(year = as.numeric (str_sub(Date, 1,4)))
```


```{r}
groundhogs_final <- groundhogs_all|> 
  left_join(Actual_weather, join_by(year == year))
```

